# Generated by Django 2.2.6 on 2019-12-04 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cliente', '0001_initial'),
        ('Livros', '0002_auto_20191121_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_emprestimo', models.CharField(max_length=255, verbose_name='ID do Empréstimo')),
                ('data_emprestimo', models.DateTimeField(verbose_name='Data do Empréstimo')),
                ('data_devolucao', models.DateField(verbose_name='Data de Devolução')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço Unitário')),
                ('quantidade', models.IntegerField(default=0, verbose_name='Quantidade')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor')),
                ('forma_pagamento', models.IntegerField(choices=[(1, 'Cartão de Crédito/Débito'), (0, 'Dinheiro')], default=0, verbose_name='Forma de Pagamento')),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Desconto')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor Total')),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Cliente.Cliente', verbose_name='Cliente')),
                ('livro', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Livros.Livro', verbose_name='Livro')),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
            },
        ),
    ]
