# Generated by Django 2.2.6 on 2019-12-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emprestimo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateTimeField(auto_now=True, verbose_name='Data do Empréstimo'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='forma_pagamento',
            field=models.IntegerField(choices=[(0, 'Dinheiro'), (1, 'Cartão de Crédito/Débito')], default=0, verbose_name='Forma de Pagamento'),
        ),
    ]
