# Generated by Django 2.2.6 on 2019-12-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emprestimo', '0003_auto_20191204_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='forma_pagamento',
            field=models.IntegerField(choices=[(0, 'Dinheiro'), (1, 'Cartão de Crédito/Débito')], default=0, verbose_name='Forma de Pagamento'),
        ),
    ]
