# Generated by Django 2.2.6 on 2019-12-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emprestimo', '0006_auto_20191204_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateTimeField(auto_now=True, help_text='Definido automaticamente.', verbose_name='Data do Empréstimo'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='forma_pagamento',
            field=models.IntegerField(choices=[(1, 'Cartão de Crédito/Débito'), (0, 'Dinheiro')], default=0, verbose_name='Forma de Pagamento'),
        ),
    ]
