# Generated by Django 2.2.6 on 2019-12-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emprestimo', '0008_auto_20191204_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='forma_pagamento',
            field=models.IntegerField(choices=[(1, 'Cartão de Crédito/Débito'), (0, 'Dinheiro')], default=0, verbose_name='Forma de Pagamento'),
        ),
    ]
