# Generated by Django 2.2.6 on 2019-12-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emprestimo', '0010_auto_20191206_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='id',
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='id_emprestimo',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ID do Empréstimo'),
        ),
    ]
